apiVersion: v1
description: "An open source geospatial data explorer"
name: "terria"
version: "0.0.1"
home: "https://github.com/TerriaJS/terriamap"
sources: ["https://github.com/TerriaJS/terriamap"]
