apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "terriamap" | trunc 63 | trimSuffix "-" | quote }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3001
{{- if .Values.global.exposeNodePorts }}
{{- if .Values.global.nodePort }}
    nodePort: {{ .Values.nodePort }}
{{- end }}
  type: NodePort
{{- else }}
  type: LoadBalancer
{{- end }}
  selector:
    service: {{ printf "%s-%s" .Release.Name "terriamap" | trunc 63 | trimSuffix "-" | quote }}
